((c-mode . ((c-basic-offset . 4)
            (c-file-style . "bsd")
            (fill-column . 78)
            (indent-tabs-mode . t)
            (tab-width . 4)
	    (c-file-offsets . ((topmost-intro      . 0)
			       (topmost-intro-cont . 0)
			       (substatement       . +)
			       (substatement-open  . 0)
			       (case-label         . +)
			       (access-label       . -)
			       (inclass            . +)
			       (inline-open        . 0)
			       (label              . *)
			       ))
	    (eval add-hook 'before-save-hook 'delete-trailing-whitespace nil t)
	    )))
